# user token
@accesstoken=101

@baseurl=http://127.0.0.1:3000

### follow
curl -XPOST {{baseurl}}/api/v1/users/1/follow \
  -H "Authorization: {{accesstoken}}"

### unfollow
curl -XDELETE {{baseurl}}/api/v1/users/2/follow \
  -H "Authorization: {{accesstoken}}"

### get sleeps
curl '{{baseurl}}/api/v1/sleeps?limit=2&cursor=105' \
  -H "Authorization: {{accesstoken}}"


### get friend_feeds
curl '{{baseurl}}/api/v1/sleeps/friend_feeds' \
  -H "Authorization: {{accesstoken}}"


### get stats
curl '{{baseurl}}/api/v1/sleeps/stats' \
  -H "Authorization: {{accesstoken}}"

### sleep start
curl -XPOST '{{baseurl}}/api/v1/sleeps' \
  -H "Authorization: {{accesstoken}}"

### sleep end
curl -XPOST '{{baseurl}}/api/v1/sleeps/954860/end' \
  -H "Authorization: {{accesstoken}}"
